### ISSUE TITLE
Question about `detailed_call`

### ISSUE THREAD

**Issue by tovrstra** [mfgustavo/glompo#8]
Does the `detailed_call` function return dimensionless residuals (already divided by sigma)?

See 
https://github.com/mfgustavo/glompo/blob/d01dd80d559884ce3ed70b71c820bc4752c938a9/glompo/interfaces/params.py#L280

To use it in combination with `make_radial_trajectory`, would something along the following lines makes sense?

```python
def wrapper(parvec):
    return f.detailed_call(parvec)[1]
make_radial_trajectory(wrapper, ...)
```

**Comment by mfgustavo** [comment]
The answer depends on if you set `scale_residuals` to `True` or `False` when you initialize. 

Your wrapper would work, however, for ReaxFF you should look at https://github.com/mfgustavo/glompo/blob/ad026b1fdf500d987b7931406c53a8e15e284741/glompo/analysis/trajectories.py#L417

This was designed to build-up sets for Reax as efficiently as possible and work around all the infinite results.

**Comment by tovrstra** [comment]
Thanks! With `scale_residuals=True`, it seems that `r_scaled = weight * (r / sigma) ** 2` is returned. Is there a ways to just get `r / sigma` (keeping the sign, dimensionless and linear in r)? Is this was the `resids` method does?

**Comment by mfgustavo** [comment]
No, unfortunately `_scale_residuals` always does `weight * (r / sigma) ** 2`. `resids` is actually similar to the wrapper you suggested above in that it only returns the residuals and nothing else.

If you would like to have residuals `r / sigma` then I suggest superclassing `ReaxFFError` and reimplementing `_scale_residuals` as you like. This would not effect the overall error result because that is calculated on the ParAMS side and can be configured via its arguments.

**Comment by tovrstra** [comment]
OK. Maybe the following is easier? When `scale_residuals=False`, does `detailed_call`, just return residuals without squaring? The bigger issue is losing sign information. Dividing by sigmas can always be done later.

**Comment by mfgustavo** [comment]
When `scale_residuals=False` then just the raw residuals (difference between prediction and reference) are returned. Dividing by the sigmas at the very end is indeed an easier solution.

**Comment by tovrstra** [comment]
Thanks. That way, it can still be decided later what to do with the residuals, which seems convenient at this stage.
